export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const UPDATE_JOBS = "UPDATE_JOBS";
export const UPDATE_JOB_APPS = "UPDATE_JOB_APPS"
export const UPDATE_JOB_SAVES = "UPDATE_JOB_SAVES"